project:
  type: book

book:
  title: "Learn Django"
  author: "Justin Shaw"
  date: "2025-11-10"
  chapters:
    - index.qmd


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



